### ISSUE TITLE
Пропуск битвы с первым монстром

### ISSUE THREAD

**Issue by SRodion** [fso13/DungeonPapperWPF#30]
Пропустился этап битвы с первым монстром, сразу перешёл к выбору кубиков и шляпу отметил как череп красным 
![image](https://user-images.githubusercontent.com/80325014/163353527-77809edf-5bee-4e64-90d2-cac208b0f5c9.png)

**Comment by SRodion** [comment]
![image](https://user-images.githubusercontent.com/80325014/163354916-2fde58e1-0b22-4165-bd7b-e023ba106411.png)
А с первым монстром было бы ещё больше...

**Comment by SRodion** [comment]
Монстр первый, кстати, даже не закрасился как пройденный

**Comment by fso13** [comment]
ага. он 4 кубик для первого раунда взял
![image](https://user-images.githubusercontent.com/47258969/163356410-8896eb9b-cb4b-496b-9fd7-2454535e69bf.png)

**Comment by fso13** [comment]
а не помнишь что сделал в этом ходу, на что кубы потратил?
