### ISSUE TITLE
Кнопка выбора квеста после завершения игры

### ISSUE THREAD

**Issue by SRodion** [fso13/DungeonPapperWPF#31]
Нужна какая-нибудь кнопка чтобы когда квест закончился и результат посмотрел можно было бы вернуться к окну выбора квеста. Иначе приходится игру закрывать и открывать.

**Comment by SRodion** [comment]
Можно как вариант сделать чтобы кнопка новая игра становилась в конце активной

**Comment by fso13** [comment]
кнопку не сделал, некуда ее лепить, а на текущую кнопку вешать логику очень геморно.
по этому сделал перезапуск окна, после закрытия окна с финальными очками

**Comment by SRodion** [comment]
Ну ок, потестируем
